import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";
import Sidebar from "@/components/Sidebar";
import { UserMenuLinks } from "@/constants/menuLinks";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EZHealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full">
      <Sidebar menuLinks={UserMenuLinks} />
      {children}
    </div>
  );
}
